const sagas = {
    LOGIN:'LOGIN',
    LOGOUT: 'LOGOUT',
    INIT_LOAD:'INIT_LOAD',
    GET_LIST_MANAGEMENTS:'GET_LIST_MANAGEMENTS',
    NEXT_GET_LIST_MANAGEMENTS:'NEXT_GET_LIST_MANAGEMENTS',
    UPDATE_MANAGEMENTS:'UPDATE_MANAGEMENTS',
    SAVE_NEW_MANAGEMENT:'SAVE_NEW_MANAGEMENT',
    SAVE_NEW_CLIENT:'SAVE_NEW_CLIENT',
    WALLET_LIST:'WALLET_LIST',
    SAVE_ACTIVITY:'SAVE_ACTIVITY',
    SAVE_TOKEN_FIREBASE: 'SAVE_TOKEN_FIREBASE',
    UPDATE_TAIL:'UPDATE_TAIL',
    UPDATE_TURN_PORTAGE:'UPDATE_TURN_PORTAGE',
    REGISTER:'REGISTER',
    NOTIFICATION:'NOTIFICATION',
    RESET_NUM_NOTIFICATION:'RESET_NUM_NOTIFICATION'
};

export default sagas;