const store = {
    LOAD :'LOAD',
    PUSH :'PUSH',
    LIST_AREAS_INFO:'LIST_AREAS_INFO',
    LIST_INST_INFO:'LIST_INST_INFO',
    LIST_EQUIP_INFO:'LIST_EQUIP_INFO',
    LAST_INSTALATION:'LAST_INSTALATION',
    LAST_EQUIP:'LAST_EQUIP',
    MANAGEMENT_TYPE:'MANAGEMENT_TYPE',
    BACK_IMAGE:'BACK_IMAGE',
};
export default store;